Adds wallet compliance guide
onflow/fcl-discovery pull request #130
Opened 2022-10-19 16:29 UTC by JeffreyDoyle

2022-10-24 22:10 UTC, chasefleming commented
@JeffreyDoyle Can you link an issue for more context please?

2022-10-24 22:17 UTC, chasefleming requested changes
Can you also link this from the readme. Probably under "Adding a Wallet to Discovery."

2022-10-24 22:17 UTC, chasefleming commented on docs/wallet-compliance-guide.md
> +This guide contains a set of critera wallets on Flow must meet in order to be accepted and included in Flow's FCL Wallet Discovery.
Would add a why here. E.g. this is done to ensure that developers and users have a seamless experience across applications, no wallet specific code is required by developers, and users can expect apps to function as expected and support FCL's open standards. 

Would also note that why services are deemed opt-in if they don't meet that criteria.

2022-10-24 22:17 UTC, chasefleming commented on docs/wallet-compliance-guide.md
> +Wallet developers are expected to ensure their wallet meets the required functionality by using the FCL Harness to test their wallet. Prior to inclusion in Flow's FCL Discovery, the Flow team will al
Would also reiterate they "why" here

2022-10-26 20:30 UTC, chasefleming requested changes
Also, still need a link from the readme in the "Adding a Wallet to Discovery" section.

2022-10-26 20:30 UTC, chasefleming commented on docs/wallet-compliance-guide.md
> +Wallets may additionally choose to support other FCL services (pre-authz, provable authentication etc), but these additional services are not reqiured to be included in Flow's FCL Wallet Descovery.
```suggestion
Wallets may additionally choose to support other FCL services (pre-authz, provable authentication etc), but these additional services are not required to be included in Flow's FCL Wallet Discovery.
```

2022-10-26 20:30 UTC, chasefleming commented on docs/wallet-compliance-guide.md
> +End users expect that wallets on FCL Discovery function as expected, and application developers that use FCL Discovery depend on it to ensure wallets meet the minimum required functionality. Other op
```suggestion
End users expect that wallets on FCL Discovery function as expected, and application developers that use FCL Discovery depend on it to ensure wallets meet the minimum required functionality. Other opt-in services (wallets with a subset of required services or limited functionality) are not expected to be provided to application developers by wallets, and thus are not required by this standard.
```

2022-10-26 21:56 UTC, gregsantos requested changes

2022-10-26 21:56 UTC, gregsantos commented on docs/wallet-compliance-guide.md
>  Wallets may additionally choose to support other FCL services (pre-authz, provable authentication etc), but these additional services are not reqiured to be included in Flow's FCL Wallet Descovery.
```suggestion
Wallets may choose to support additional FCL services (pre-authz, account-proof, etc.), but these additional services are not required to be included in Flow's FCL Wallet Discovery.
```

2022-10-26 21:56 UTC, gregsantos commented on docs/wallet-compliance-guide.md
> +End users expect that wallets on FCL Discovery function as expected, and application developers that use FCL Discovery depend on it to ensure wallets meet the minimum required functionality. Other op
```suggestion
End users and application developers using FCL Discovery should be able to rely on included wallets meeting the minimum required functionality. Other opt-in services are not expected to be provided to application developers by wallets, and thus are not enforced by this standard.
```

2022-10-26 21:56 UTC, gregsantos commented on docs/wallet-compliance-guide.md
>  In order to be included in Flow's FCL Wallet Discovery, new wallets must prove their functionality, and continue to prove their functionality on a recurrent basis from time to time. Wallets that fail
```suggestion
In order to be included in Flow's FCL Wallet Discovery, new wallets must prove their functionality, and continue to prove their functionality on a recurrent basis from time to time. Wallets that fail to prove their functionality may be subject to removal from FCL Discovery until the required functionality is restored.
```

2022-10-26 22:30 UTC, gregsantos approved these changes

2022-10-31 18:09 UTC, chasefleming approved these changes

2022-10-31 18:22 UTC, merged