update to use local service config when network is emulator
onflow/fcl-discovery pull request #173
Opened 2024-01-05 23:50 UTC by bthaile

closes: https://github.com/onflow/fcl-discovery/issues/172

Update to support emulator as a network, use local service config. This gives the user dev wallet to interact with the emulator.

2024-01-06 00:04 UTC, chasefleming approved these changes

2024-01-06 00:30 UTC, jribbink requested changes
I'm curious why we need to define an endpoint for "emulator" since "local" exists & this is the de facto standard naming for the local network in FCL.  What is the use case here?  Is this request coming from FCL?

2024-01-08 17:37 UTC, nialexsan approved these changes

2024-01-08 18:12 UTC, bthaile commented
A few thoughts, 
there is no network "local" there is emulator, dedicated by flow-cli `--netowrk emulator` this PR is an effort standardize network names. Also FLIX gets it's network names from flow-cli terminology and creates network sections for emulator, testnet and mainnet.

2024-01-08 18:12 UTC, bthaile commented
> A few thoughts,
> there is no network "local" there is emulator, dedicated by flow-cli `--netowrk emulator` this PR is an effort standardize network names. Also FLIX gets it's network names from flow-cli terminology and creates network sections for emulator, testnet and mainnet.

A few thoughts,
there is no network "local" there is emulator, dedicated by flow-cli --netowrk emulator this PR is an effort standardize network names. Also FLIX gets it's network names from flow-cli terminology and creates network sections for emulator, testnet and mainnet.

2024-01-08 18:32 UTC, jribbink approved these changes

2024-01-08 18:32 UTC, merged